# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[cmake]
version = "3.31"
cmkr-include = "cmkr.cmake"

[project]
name = "kev1n"
languages = ["CXX"]

[variables]
CMAKE_EXPORT_COMPILE_COMMANDS = true

# dependencies
[fetch-content.nlohmann_json]
git = "https://github.com/nlohmann/json"
tag = "v3.12.0"

[target.kev1n]
type = "executable"
sources = [
    "src/**.cpp",
    "src/**.hpp"
]
include-directories = [
    "vendor/raylib-6.0_webassembly/include"
]
link-directories = [
    "vendor/raylib-6.0_webassembly/lib"
]
link-libraries = [
    "raylib.web",
    "nlohmann_json::nlohmann_json"
]
link-options = ["-sUSE_GLFW=3"]
precompile-headers = ["src/pch.hpp"]
compile-features = ["cxx_std_23"]

[target.kev1n.properties]
SUFFIX = ".html"
