# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[cmake]
version = "3.31"
cmkr-include = "cmkr.cmake"

[project]
name = "kev1n"
languages = ["CXX"]

[variables]
CMAKE_EXPORT_COMPILE_COMMANDS = true

# dependencies
[fetch-content.nlohmann_json]
git = "https://github.com/nlohmann/json"
tag = "v3.12.0"
[fetch-content.cpr]
git = "https://github.com/libcpr/cpr/"
tag = "1.14.2"
options = { CPR_CURL_USE_LIBPSL = false, BUILD_EXAMPLES = false, BUILD_SHARED_LIBS = false }

[target.kev1n]
type = "executable"
sources = [
    "src/**.cpp",
    "src/**.hpp"
]
link-libraries = [
    "raylib",
    "nlohmann_json::nlohmann_json",
    "cpr::cpr"
]
precompile-headers = ["src/pch.hpp"]
compile-features = ["cxx_std_23"]

[target.kev1n.macos]
include-directories = [
    "vendor/raylib-6.0_macos/include"
]
link-directories = [
    "vendor/raylib-6.0_macos/lib"
]

[target.kev1n.windows]
link-libraries = [
    "winmm",
    "gdi32",
    "user32",
    "shell32"
]
compile-options = ["/W4"]
include-directories = [
    "vendor/raylib-6.0_win64_msvc16/include"
]
link-directories = [
    "vendor/raylib-6.0_win64_msvc16/lib"
]
